//*****************************************************************************
// Copyright (c) 2014 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions
//   are met:
// 
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
// 
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the  
//   distribution.
// 
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// This file was automatically generated by the Tiva C Series PinMux Utility
// Version: 1.0.4
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "my_switch_PinMux.h"
#include "inc/hw_types.h"
#include "inc/hw_memmap.h"
#include "inc/hw_gpio.h"
#include "driverlib/sysctl.h"
#include "driverlib/pin_map.h"
#include "driverlib/gpio.h"
#include "inc/tm4c123gh6pm.h"

#define GREEN_MASK 0x08

//*****************************************************************************
//! Create and implement two new projects my_switch_PinMux and my_toggle_PinMux, which 
//! perform the same functions as my_switch and my_toggle did, respectively. my_switch and 
//! my_toggle are based on the two projects you implemented in Lab 3. In my_switch_PinMux, when 
//! SW1 is pressed, the green LED is turned off, otherwise the green LED is on. 
//! my_toggle_PinMux makes the blue LED flash every one second (i.e. the LED on for one second 
//! and then off for one second, repeatedly).
//
//


void
PortFunctionInit(void)
{
    //
    // Enable Peripheral Clocks 
    //
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);

    //
    // Enable pin PF4 for GPIOInput
    //
    GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_4);

    //
    // Enable pin PF3 for GPIOOutput
    //
    GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_3);
	//
	
	//
		GPIO_PORTF_PUR_R |= 0x10; //enable pull up resistor on PF4
}
int main(void){
//In my_switch_PinMux, when 
//SW1 is pressed, the green LED is turned off, otherwise the green LED is on.
// GREEN = 0X08
	PortFunctionInit();// initialize

	while(1){
	
	if(GPIOPinRead(GPIO_PORTF_BASE,GPIO_PIN_4)==0X10){// read from pin4 to see if SW1 is not pressed
		GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, GREEN_MASK);// if its not, turn led on
	}
	else{GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, 0x00);}// if it is turn it off
	}
}
